services:
  openmetadata:
    image: openmetadata/server:latest
    platform: linux/amd64
    ports:
      - "8585:8585"
    environment:
      - OPENMETADATA_CLUSTER_NAME=openmetadata
    volumes:
      - openmetadata_data:/opt/openmetadata

volumes:
  openmetadata_data:
